index:
    path: /
    controller: App\Controller\DefaultController::index

advisor_create:
    path: /advisor
    methods: POST
    controller: App\Controller\AdvisorController:create

advisors_get:
    path: /advisor
    methods: GET
    controller: App\Controller\AdvisorController:getAdvisor

advisor_delete:
    path: /advisor/{id}
    methods: DELETE
    controller: App\Controller\AdvisorController:delete

advisor_update:
    path: /advisor/{id}
    methods: PATCH
    controller: App\Controller\AdvisorController:update

advisor_get:
    path: /advisor/{id}
    methods: GET
    controller: App\Controller\AdvisorController:getAdvisor